INSERT INTO `#__js_ticket_emailtemplates` (`id`, `templatefor`, `title`, `subject`, `body`, `created`, `status`) VALUES (26,'mail-rpy-closed','',	'JS Tickets: Ticket has been closed',	'<p>Your ticket {TICKET_SUBJECT} has been closed.</p>\n<p>You can not reply to a closed ticket</p>\n<p>	<span style=\"color: red;\">	<strong>*DO NOT REPLY TO THIS E-MAIL*</strong>	</span>	<br />\nThis is an automated e-mail message sent from our support system. Do not reply to this e-mail as we wonot receive your reply!</p>\n',NULL,0),(27,'mail-feedback','','JS Tickets: Give Us Your Feedback','<p>Dear {USER_NAME}, Your ticket {TICKET_SUBJECT} having tracking id {TRACKING_ID} has been closed on {CLOSE_DATE}.\n We would really appreciate if you took the time to tell us how well our staff member helped you in your problem..</p>\n<p>	{LINK}link text{/LINK}	</p>\n<p>	\n	<span style=\"color: red;\">	<strong>*DO NOT REPLY TO THIS E-MAIL*</strong>	</span>	<br />\nThis is an automated e-mail message sent from our support system. Do not reply to this e-mail as we wonot receive your reply!</p>\n',NULL,0);

INSERT INTO `#__js_ticket_fieldsordering` (`id`, `field`, `fieldtitle`, `ordering`, `section`, `fieldfor`, `published`, `sys`, `cannotunpublish`, `required`,`cannotsearch`,`cannotshowonlisting`,`isvisitorpublished`) VALUES (15, 'rating', 'Rating', 1, '10', 2, 1, 0, 0, 0, 0, 0, 1),(16, 'remarks', 'Remarks', 2, '10', 2, 1, 0, 0, 0, 0, 0, 1);

ALTER TABLE `#__js_ticket_tickets`  ADD `feedbackemail` TINYINT NOT NULL  AFTER `attachmentdir`;

INSERT INTO `#__js_ticket_config` (`configname`, `configvalue`, `configfor`) VALUES('wp_default_role','subscriber','default'),('captcha_on_registration','1','default'),('cplink_register_user','1','default'),('cplink_feedback_staff','1','default'),('feedback_email_delay_type','1','default'),('feedback_email_delay','30','default'),('ticket_feedback_user','1','default'),('ticket_overdue_type','1','default'),('reply_to_closed_ticket','1','default'),('visitor_message','Thank You for contacting us. A support ticket request has been created, A representative will be getting back to you shortly.<br/>\r\nSupport Team','default');

REPLACE INTO `#__js_ticket_config` (`configname`, `configvalue`, `configfor`) VALUES ('versioncode','2.0.1','default');
REPLACE INTO `#__js_ticket_config` (`configname`, `configvalue`, `configfor`) VALUES ('productversion','201','default');
